### ISSUE TITLE
Remote Post Problem: Tags (Diaspora) and Links (GnuSocial/Statusnet)

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redmatrix#136]
_From @HeathenMan on October 7, 2014 18:53_

Tags on Remote Posts in Diaspora are linking to the red hub, should deliver it as it is to the remote!
I cant tag-post trough red cause it wont use the diaspora tag system.
2th problem is the URL delivery on GnuSocial/Statusnet. If Link is entered, crossposting will result in #^Link Link [red post: #^Link (clickable)]
where ^Link means no href (not clickable)
Diaspora: http://r.8.je/2q
GnuSocial: https://quitter.se/heathenman
Red: https://gurus.red/channel/heathenman-red

Didnt get time to check if its app fault (android- http://r.8.je/1m6 )
edit: both are not app related

_Copied from original issue: friendica/red#624_

**Comment by jeroenpraat** [comment]
_From @friendica on October 28, 2014 3:27_

> Tags on Remote Posts in Diaspora are linking to the red hub, should deliver it as it is to the remote!

That's one opinion. When a network steals the tags from the network that created them it is called tag theft. We've had long discussions about this with the Diaspora folks. Tag theft actually favours centralisation, and even the developers there agree. 

If you look at https://zothub.com/help/diaspora_compat you will see 

> We currently allow tags to be hijacked by default. We will provide an option to allow you to prevent the other end of the network from hijacking your tags and point them at its own resources.

We originally blocked tag theft by default but this was reverted some time ago. You may have been on an older image. So this should be fixed.  

GNU/Social (statusnet) is an addon that was ported from Friendica. It is currently not being maintained by anybody and is not a core part of the project. I will leave this issue open.

**Comment by redmatrix** [comment]
If GNU/Social links are still an issue please re-open a bug in redmatrix-addons. This is not a core issue.
